name: flutter_xmshop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5 #Gext框架
  dio: ^4.0.6 #网络请求库
  flutter_screenutil: ^5.6.0 #屏幕适配组件
  flutter_swiper_view: ^1.1.8 #滚动轮播图

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
  - family: CustomFont
    fonts:
      - asset: assets/iconfont.ttf

