name: flutter_xmshop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5 #Gext框架
  dio: ^4.0.6 #网络请求库
  flutter_screenutil: ^5.6.0 #屏幕适配组件
  flutter_swiper_view: ^1.1.8 #滚动轮播图
  flutter_staggered_grid_view: ^0.6.2 #瀑布流
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
  - family: CustomFont
    fonts:
      - asset: assets/fonts/iconfont.ttf
  #图片资源
  assets:
    - assets/images/xiaomiBanner.png
    - assets/images/2.0x/xiaomiBanner.png
    - assets/images/3.0x/xiaomiBanner.png
    - assets/images/xiaomiBanner2.png
    - assets/images/2.0x/xiaomiBanner2.png
    - assets/images/3.0x/xiaomiBanner2.png
    - assets/images/tuijian01.png
    - assets/images/2.0x/tuijian01.png
    - assets/images/3.0x/tuijian01.png
    - assets/images/tuijian02.png
    - assets/images/2.0x/tuijian02.png
    - assets/images/3.0x/tuijian02.png
    - assets/images/tuijian03.png
    - assets/images/2.0x/tuijian03.png
    - assets/images/3.0x/tuijian03.png

